# Generated by Django 2.0.6 on 2018-06-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpUsage',
            fields=[
                ('ip', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('usage', models.IntegerField(default=0)),
            ],
        ),
    ]
